version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydbDoctor
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
networks:
  webnet:
volumes:
  postgres-data:
  pgdata:
