version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - webnet
    env_file:
      - .env
    expose:
      - "5436"
    ports:
      - 5436:5436
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
