version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - webnet
    volumes:
      - db:/var/lib/postgresql/data
networks:
      webnet:
volumes:
  db:
    driver: local