version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test_project:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install --legacy-peer-deps
          name: Install packages
      - run:
          command: npm run test
          name: Test Packages
      
workflows:
  test_my_app:
    jobs:
      - test_project